services:
  api:
    build: ./
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
  
  testDB:
    image: postgres
    ports:
      - '6543:5432'
    volumes:
      - test_postgres:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres:
  test_postgres:
