services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env.docker

  db:
    image: postgres:17
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    command: celery -A auto_deletions.celery_app worker -l info
    depends_on:
      - redis
      - db
    env_file:
      - .env.docker

  celery_beat:
    build: .
    command: celery -A auto_deletions.celery_app beat -l info
    depends_on:
      - redis
      - db
    env_file:
      - .env.docker

volumes:
  postgres:
  redis_data:
